basket/urls.py
from django.urls import path, include
from basket import views
app_name = 'Game'

urlpatterns = [
    path('players/list', views.players_list, name="players_list"),   
    path('teams/list', views.teams_list, name="teams_list"),   
    path('coachs/list', views.coachs_list, name="coachs_list"),   
    path('matchs/list', views.matchs_list, name="matchs_list"),

    path('Coach/a', views.indexCoach, name='indexCoach'),
    path('Coach/add/', views.Coach_create, name='Coach_add'),
    path('Coach/update/<int:pk>', views.Coach_update, name='Coach_update'),
    path('Coach/delete/<int:pk>', views.Coach_delete, name='Coach_delete'),

    path('Team/a', views.indexTeam, name='indexTeam'),
    path('Team/add/', views.Team_create, name='Team_create'),
    path('Team/update/<int:pk>', views.Team_update, name='Team_update'),
    path('Team/delete/<int:pk>', views.Team_delete, name='Team_delete'),

    path('Player/a', views.indexPlayer, name='indexPlayer'),
    path('Player/add/', views.Player_create, name='Player_add'),
    path('Player/update/<int:pk>', views.Player_update, name='Player_update'),
    path('Player/delete/<int:pk>', views.Player_delete, name='Player_delete'),
    path('', views.home, name="home"),   
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basket/', include('basket.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

basket/models.py
from django.db import models



"""
Nombre entrenador
Edad
Email
Rut
Apodo
"""
class Coach(models.Model):
    name = models.CharField(max_length=150)
    age = models.PositiveIntegerField()
    email = models.EmailField()
    rut = models.CharField(max_length=12)
    nickname = models.CharField(max_length=80)

    def __str__(self):
        return self.name

"""
Nombre del team
Descripción del team
Logo del team
Código de equipo
"""
class Team(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField()
    code = models.CharField(max_length=20, unique=True)
    logo = models.ImageField(upload_to='teams/')
    coach = models.OneToOneField(Coach, on_delete=models.CASCADE)

    def count_player(self):
        return Player.objects.filter(team=self.pk).count()

    def __str__(self):
        return self.name

"""
Nombre jugador
Apodo
Fecha de nacimiento
Edad
Rut
Email
Estatura
Peso
Fotografía
Posición de juego (opciones: Base, Escolta, Alero, Ala-pivot, Pivot)
"""

POSITION_PLAYER = (
    ('BA', 'Base'),
    ('ES', 'Escolta'),
    ('AL', 'Alero'),
    ('AP', 'Ala-pivot'),
    ('PI', 'Pivot'),
)

class Player(models.Model):
    name = models.CharField(max_length=150)
    nickname = models.CharField(max_length=80)
    birthday = models.DateField()
    age = models.PositiveIntegerField()
    rut = models.CharField(max_length=12)
    email = models.EmailField()
    height = models.PositiveIntegerField(help_text='in centimeters')
    weight = models.PositiveIntegerField(help_text='in grams')
    photo = models.ImageField(upload_to='players/')
    position = models.CharField(choices=POSITION_PLAYER, max_length=2)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return '{name} ({team})' . format(name=self.name, team=self.team)



class Roster(models.Model):
    name = models.CharField(max_length=150)
    player = models.ManyToManyField(Player)

    def __str__(self):
        return self.name


class Match(models.Model):
    name = models.CharField(max_length=150)
    team1 = models.ForeignKey(Roster, related_name='team1', on_delete=models.CASCADE)
    team2 = models.ForeignKey(Roster, related_name='team2', on_delete=models.CASCADE)
    date = models.DateTimeField()

    def __str__(self):
        return '{name} ({team1} vs {team2})'.format(
            name=self.name,
            team1=self.team1,
            team2=self.team2
        ) 

basket/forms.py
from django import forms
from .models import *

class CoachForm(forms.ModelForm):
    class Meta:
        model = Coach
        fields = '__all__'

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = '__all__'

class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = '__all__'

basket/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from basket.models import (
    Team,
    Player,
    Coach,
    Match
)

def players_list(request):
    template_name = 'players_list.html'
    data = {}

    teams = Team.objects.all()

    for team in teams:
        team.players = Player.objects.filter(team=team)

    data['teams'] = teams

    return render(request, template_name, data)

def teams_list(request):
    template_name = 'teams_list.html'
    data = {}

    data['teams'] = Team.objects.all()
    return render(request, template_name, data)

def coachs_list(request):
    template_name = 'coach_list.html'
    data = {}
    data['coachs'] = Coach.objects.all()

    return render(request, template_name, data)


def matchs_list(request):
    template_name = 'matchs_list.html'
    data = {}

    data['matchs'] = Match.objects.all()

    return render(request, template_name, data)

def home(request):
    template_name = 'home.html'
    data = {}

    data['last_5_matchs'] = Match.objects.all().order_by('-pk')[:5]
    data['last_5_players'] = Player.objects.all().order_by('-pk')[:5]
    data['teams'] = Team.objects.all()

    return render(request, template_name, data)


def indexCoach(request):
    template = 'Coach/list_coach.html'
    coachs = Coach.objects.all()
    context = {"Coach": coachs}
    return render(request, template, context)

def Coach_create(request):
    template = 'Coach/form.html'
    form = CoachForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('Game:indexCoach')
    context = {"form": form}
    return render(request, template, context)


def Coach_update(request, pk):
    template = 'Coach/form.html'
    Coachs = get_object_or_404(Coach, pk=pk)
    form = CoachForm(request.POST or None, instance=Coachs)
    if form.is_valid():
        form.save()
        return redirect('Game:indexCoach')
    context = {"form": form}
    return render(request, template, context)

def Coach_delete(request, pk):
    template = 'Coach/delete.html'
    Coachs = get_object_or_404(Coach, pk=pk)
    if request.method == 'POST':
        Coachs.delete()
        return redirect('Game:indexCoach')
    context = {"Coach": Coach}
    return render(request, template, context)

def indexTeam(request):
    template_name = 'teams_list.html'
    data = {}

    data['teams'] = Team.objects.all()
    return render(request, template_name, data)


def Team_create(request):
    template = 'Team/form.html'
    data = {}
    form = TeamForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('Game:indexTeam')
    context = {"form": form}
    return render(request, template, context)


def Team_update(request, pk):
    template = 'Team/form.html'
    teams = get_object_or_404(Team, pk=pk)
    form = TeamForm(request.POST or None, instance=teams)
    if form.is_valid():
        form.save()
        return redirect('Game:indexTeam')
    context = {"form": form}
    return render(request, template, context)

def Team_delete(request, pk):
    template = 'Team/delete.html'
    Teams = get_object_or_404(Team, pk=pk)
    if request.method == 'POST':
        Teams.delete()
        return redirect('Game:indexTeam')
    context = {"Team": Teams}
    return render(request, template, context)


def indexPlayer(request):
    template = 'Player/Player_list.html'
    Players = Player.objects.all()
    context = {"Player": Players}
    return render(request, template, context)


def Player_create(request):
    template = 'Player/form.html'
    form = PlayerForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('Game:indexPlayer')
    context = {"form": form}
    return render(request, template, context)


def Player_update(request, pk):
    template = 'Player/form.html'
    Players = get_object_or_404(Player, pk=pk)
    form = PlayerForm(request.POST or None, instance=Players)
    if form.is_valid():
        form.save()
        return redirect('Game:indexPlayer')
    context = {"form": form}
    return render(request, template, context)

def Player_delete(request, pk):
    template = 'Player/delete.html'
    Players = get_object_or_404(Player, pk=pk)
    if request.method == 'POST':
        Players.delete()
        return redirect('Game:indexPlayer')
    context = {"Player": Players}
    return render(request, template, context)

basket/templates/Coach/delete.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% block content %}
<form class="" method="post">
  {% csrf_token %}
  Are you sure want to delete it?
  <input type="submit" name="" value="submit">
</form>
{% endblock %}

basket/templates/Coach/form.html
{% extends 'base.html' %}
{% block title %}
fbv form
{% endblock %}
{% block content %}
<form class="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="" value="submit">
</form>
{% endblock %}

basket/templates/Coach/list_coach.html
{% extends 'base.html' %}
{% block title %}
Coach
{% endblock %}
{% block content %}
<a href="{% url 'Game:home' %}">back to home</a><br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>name</th>
      <th>age</th>
      <th>email</th>
      <th>rut</th>
      <th>nickname</th>
      <th>Acciones</th>

    </tr>
  </thead>
  <tbody>
    <a href="{% url 'Game:Coach_add' %}">add</a>
    {% for b in Coach %}
    <tr>
      <td>{{ b.name }}</td>
      <td>{{ b.age }}</td>
      <td>{{ b.email }}</td>
      <td>{{ b.rut }}</td>
      <td>{{ b.nickname }}</td>
      <td>
        <a href="{% url 'Game:Coach_update' b.id %}">edit</a>
        <a href="{% url 'Game:Coach_delete' b.id %}">delete</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

basket/templates/Player/Player_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


  <title>{ </title>
</head>
<body>


<a href="{% url 'Game:home' %}">back to home</a><br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>name</th>
      <th>nickname</th>
      <th>birthday</th>
      <th>age</th>
      <th>rut</th>
      <th>email</th>
      <th>height</th>
      <th>weight</th>
      <th>photo</th>
      <th>team</th>
      <th>position</th>
      <th>Activity</th>
    </tr>
  </thead>
  <tbody>
    <a href="{% url 'Game:Player_add' %}">add</a>
    {% for b in Player %}
    <tr>
      <td>{{ b.name }}</td>
      <td>{{ b.nickname }}</td>
      <td>{{ b.birthday }}</td>
      <td>{{ b.age }}</td>
      <td>{{ b.rut }}</td>
      <td>{{ b.email }}</td>
      <td>{{ b.height }}</td>
      <td>{{ b.weight }}</td>
      <td>{{ b.photo }}</td>
      <td>{{ b.team }}</td>
      <td>{{ b.position }}</td>

      <td>
        <a href="{% url 'Game:Player_update' b.id %}">edit</a>
        <a href="{% url 'Game:Player_delete' b.id %}">delete</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>


</body>
</html>

basket/templates/Player/delete.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% block content %}
<form class="" method="post">
  {% csrf_token %}
  Are you sure want to delete it?
  <input type="submit" name="" value="submit">
</form>
{% endblock %}

basket/templates/Player/form.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


  <title>{ </title>
</head>
<body>

<form class="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="" value="submit">
</form>

</body>
</html>

basket/templates/Team/Team_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


  <title>{ </title>
</head>
<body>


<a href="{% url 'Game:home' %}">back to home</a><br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>name</th>
      <th>description</th>
      <th>code</th>
      <th>coach</th>
      <th>Activity</th>
    </tr>
  </thead>
  <tbody>
    <a href="{% url 'Game:Team_create' %}">add</a>
    {% for b in Team %}
    <tr>
      <td>{{ b.name }}</td>
      <td>{{ b.description }}</td>
      <td>{{ b.code }}</td>
      <td>{{ b.coach }}</td>
      <td>
        <a href="{% url 'Game:Team_update' b.id %}">edit</a>
        <a href="{% url 'Game:Team_delete' b.id %}">delete</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>


</body>
</html>

basket/templates/Team/delete.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% block content %}
<form class="" method="post">
  {% csrf_token %}
  Are you sure want to delete it?
  <input type="submit" name="" value="submit">
</form>
{% endblock %}

basket/templates/Team/form.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


  <title>{ </title>
</head>
<body>

<form class="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="" value="submit">
</form>

</body>
</html>

basket/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  {% block content %}
  {% endblock %}
</body>
</html>

basket/templates/coach_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Coach</title>
</head>
<body>
    <body>
        <ul>
            {% for coach in coachs %}
            <li>{{coach.name}} (<strong>{{coach.team.name}}</strong>)</li>
            {% endfor %}
        </ul>
    </body>
    </html>
</body>
</html>

basket/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>Basket App</title>



</head>
<body>
    <br>
    <br>
    <br>
    <h1>Basket App</h1>
    <br>
    <br>
    <br>
    

    <ul>
        <a href="{% url 'Game:indexCoach' %}"> Entrenadores</a>
        <br>
        <a href="{% url 'Game:indexTeam' %}">Equipos</a>
        <br>
        <a href="{% url 'Game:indexPlayer' %}">Jugadores</a>
        <br>
        <a href="{% url 'Game:matchs_list' %}">Partidas jugadas</a>
        <br>

    </ul>
    <h2>Last 5 players</h2>
        
    <ul>
        {% for player in last_5_players %}
        <li>{{player.name}} ({{player.nickname}})</li>
        {% endfor %}
    </ul>

    <h2>Last 5 Matchs</h2>
    <ul>
        {% for match in last_5_matchs %}
        <li>{{match.team1.player.first.team.name}} <strong>VS</strong> {{match.team2.player.first.team.name}}</li>
        {% endfor %}
    </ul>
    
    <h2>Teams</h2>
    <ul>
        {% for team in teams %}
        <li>{{team.name}} (tiene {{team.count_player}} jugadores)</li>
        {% endfor %}
    </ul>

</body>
</html>

basket/templates/matchs_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    
    <title>Coach</title>
</head>
<body>
    <body>
        <ul>
            {% for match in matchs %}
            <br>
            <br>
            <li>{{match.team1.player.first.team.name}} <strong>VS</strong> {{match.team2.player.first.team.name}}</li>
            <br>
            <br>
            {% endfor %}
        </ul>
    </body>
    </html>
</body>
</html>

basket/templates/players_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Player list</title>
</head>
<body>

    {% for team in teams %}
        <h2>{{team.name}}</h2>
        {% for player in team.players %}
        <li>{{player.name}}</li>
        {% endfor %}


    {% endfor %}
    
</body>
</html>

basket/templates/teams_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


  <title>{ </title>
</head>
<body>

<a href="{% url 'Game:home' %}">back to home</a><br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>name</th>
      <th>description</th>
      <th>code</th>
      <th>coach</th>
      <th>Activity</th>
    </tr>
  </thead>
  <tbody>
    <a href="{% url 'Game:Team_create' %}">add</a>
    {% for b in teams %}
    <tr>
      <td>{{ b.name }}</td>
      <td>{{ b.description }}</td>
      <td>{{ b.code }}</td>
      <td>{{ b.coach }}</td>
      <td>
        <a href="{% url 'Game:Team_update' b.id %}">edit</a>
        <a href="{% url 'Game:Team_delete' b.id %}">delete</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>


</body>
</html>